const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>new Date().toISOString().slice(0,10), uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
let db={colonies:[],feedings:[],events:[],growthRecords:[],tasks:[],inventory:[],fauna:[],observations:[],appConfig:{},metadata:{}};
let route='home', selected=null, filter='all', idb=null;
const nav=[['home','⌂','Inicio'],['colonies','🐜','Colonias'],['records','✎','Diario'],['stats','▥','Datos'],['more','•••','Más']];
function save(){db.metadata={...(db.metadata||{}),schemaVersion:'4.0.0',updatedAt:new Date().toISOString()};localStorage.setItem('antelmo.v4',JSON.stringify(db))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
function daysSince(d){if(!d)return null;return Math.max(0,Math.floor((new Date(today())-new Date(d))/86400000))}
function colonyName(id){return db.colonies.find(c=>String(c.id)===String(id))?.name||'General'}
function lastFeeding(id){return db.feedings.filter(x=>String(x.colonyId)===String(id)).sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0]}
function totals(){const c=db.colonies.filter(x=>x.status!=='En tránsito');return{colonies:c.length,workers:c.reduce((a,x)=>a+(+x.workers||0),0),queens:c.reduce((a,x)=>a+(+x.queens||0),0),species:new Set(c.map(x=>x.species).filter(Boolean)).size}}
async function boot(){
  const v4=localStorage.getItem('antelmo.v4'),v3=localStorage.getItem('antelmo.v3');
  if(v4){try{db=JSON.parse(v4)}catch{}}
  else if(v3){try{db=JSON.parse(v3);save()}catch{}}
  else {db=await fetch('data.json').then(r=>r.json());save()}
  db.feedings ||= [];db.events ||= [];db.growthRecords ||= [];db.tasks ||= [];db.inventory ||= [];db.fauna ||= [];db.observations ||= [];
  await initIDB();applyTheme();render();
  if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js').then(r=>r.update()).catch(()=>{})}
}
function applyTheme(){const dark=(db.appConfig?.theme==='dark');document.body.classList.toggle('dark',dark);$('#themeBtn').textContent=dark?'☀':'☾'}
function renderNav(){$('#nav').innerHTML=nav.map(([r,i,l])=>`<button data-route="${r}" class="${route===r?'active':''}"><b>${i}</b>${l}</button>`).join('');$$('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;selected=null;render()})}
function render(){renderNav();$('#fab').style.display=['home','colonies','records'].includes(route)?'block':'none';const a=$('#app');if(route==='home')a.innerHTML=home();if(route==='colonies')a.innerHTML=selected?colonyDetail(selected):colonies();if(route==='records')a.innerHTML=records();if(route==='stats')a.innerHTML=stats();if(route==='more')a.innerHTML=more();bind();loadCovers()}
function home(){const t=totals(),pending=db.tasks.filter(x=>x.status!=='Completada');return `<section class="hero"><h2>Hola, Elmo 🌿</h2><p>Todo tu pequeño ecosistema, organizado en un solo sitio.</p><div class="metric-grid"><div class="metric"><b>${t.colonies}</b><span>colonias</span></div><div class="metric"><b>${t.workers}</b><span>obreras</span></div><div class="metric"><b>${t.queens}</b><span>reinas</span></div><div class="metric"><b>${t.species}</b><span>especies</span></div></div></section>
<div class="section-title"><div><h2>Acciones rápidas</h2><p>Registra lo importante en segundos</p></div></div><div class="quick-grid">${[['feed','🍯','Alimentación','Comida, cantidad y respuesta'],['event','📅','Evento','Mudanza, limpieza o incidencia'],['growth','📈','Recuento','Actualiza obreras y cría'],['photo','📷','Fotografía','Añade una foto a la colonia']].map(x=>`<button class="quick" data-quick="${x[0]}"><i>${x[1]}</i><b>${x[2]}</b><span>${x[3]}</span></button>`).join('')}</div>
<div class="section-title"><div><h2>Colonias</h2><p>Vista rápida del estado actual</p></div><button class="link-btn" data-go="colonies">Ver todas</button></div><div class="cards">${db.colonies.slice(0,5).map(colonyCard).join('')}</div>
<div class="section-title"><div><h2>Recordatorios</h2><p>${pending.length} pendientes</p></div></div><div class="cards">${pending.slice(0,4).map(taskCard).join('')||'<div class="card empty">No tienes tareas pendientes 🎉</div>'}</div>`}
function colonyCard(c){const lf=lastFeeding(c.id),d=daysSince(lf?.date);return `<article class="card colony-card" data-colony="${esc(c.id)}"><div class="avatar" id="cover-${esc(c.id)}">🐜</div><div><h3>${esc(c.name)}</h3><div class="latin">${esc(c.species||'Especie sin confirmar')}</div><div class="sub">${esc(c.workers??'—')} obreras · ${d==null?'sin alimentación registrada':`alimentada hace ${d} d`}</div></div><span class="chip">${esc(c.status||'Sin estado')}</span></article>`}
function taskCard(t){return `<div class="card"><b>${esc(t.title)}</b><div class="sub">${esc(t.dueDate||'Sin fecha')} · ${esc(t.priority||'Normal')}</div><div class="actions"><button class="button secondary" data-done="${esc(t.id)}">Marcar hecha</button></div></div>`}
function colonies(){return `<div class="section-title"><div><h2>Mis colonias</h2><p>${db.colonies.length} fichas activas</p></div><button class="button" data-new-colony>＋ Colonia</button></div><div class="tabs">${['all','Crecimiento','Estable','En observación','En tránsito'].map(x=>`<button class="${filter===x?'active':''}" data-filter="${x}">${x==='all'?'Todas':x}</button>`).join('')}</div><div class="cards">${db.colonies.filter(c=>filter==='all'||c.status===filter).map(colonyCard).join('')||'<div class="empty">No hay colonias en esta categoría.</div>'}</div>`}
function colonyDetail(id){const c=db.colonies.find(x=>String(x.id)===String(id));if(!c)return colonies();const lf=lastFeeding(id),growth=db.growthRecords.filter(x=>String(x.colonyId)===String(id)).sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0];return `<button class="link-btn" data-back>‹ Volver</button><div class="section-title"><div><h2>${esc(c.name)}</h2><p><i>${esc(c.species||'Sin confirmar')}</i></p></div><button class="button secondary" data-edit-colony="${esc(c.id)}">Editar</button></div><section class="card"><div class="colony-card" style="padding:0;border:0;box-shadow:none"><div class="avatar" id="cover-${esc(c.id)}">🐜</div><div><h3>${esc(c.commonName||c.name)}</h3><div class="sub">Fundada: ${esc(c.founded||'—')}</div><div class="sub">Origen: ${esc(c.origin||'—')}</div></div><span class="chip">${esc(c.status||'—')}</span></div></section>
<div class="metric-grid" style="margin-top:12px"><div class="card"><b style="font-size:24px">${esc(c.workers??'—')}</b><div class="sub">obreras</div></div><div class="card"><b style="font-size:24px">${esc(c.queens??'—')}</b><div class="sub">reinas</div></div><div class="card"><b style="font-size:24px">${growth?.eggs??c.brood?.eggs??'—'}</b><div class="sub">huevos</div></div><div class="card"><b style="font-size:24px">${growth?.larvae??c.brood?.larvae??'—'}</b><div class="sub">larvas</div></div></div>
<div class="section-title"><div><h2>Cuidados</h2><p>Últimos datos registrados</p></div></div><div class="cards"><div class="card"><b>🍯 Alimentación</b><div class="sub">${lf?`${esc(lf.food)} · ${esc(lf.date)}`:'Sin registros'}</div></div><div class="card"><b>🏠 Instalación</b><div class="sub">${esc(c.location||c.setup?.nestType||'Sin información')}</div></div><div class="card"><b>📝 Notas</b><div class="sub">${esc(c.notes||'Sin notas')}</div></div></div>
<div class="section-title"><div><h2>Galería</h2><p>Fotos guardadas en este dispositivo</p></div><button class="button secondary" data-photo-for="${esc(c.id)}">Añadir</button></div><div id="gallery" class="gallery"><div class="empty">Cargando…</div></div>`}
function records(){const all=[...db.events.map(x=>({...x,kind:'Evento',title:x.title||x.type||'Evento'})),...db.feedings.map(x=>({...x,kind:'Alimentación',title:x.food||'Alimentación'})),...db.growthRecords.map(x=>({...x,kind:'Recuento',title:`${x.workers??'—'} obreras`}))].sort((a,b)=>String(b.date).localeCompare(String(a.date)));return `<div class="section-title"><div><h2>Diario</h2><p>${all.length} registros</p></div></div><div class="tabs">${['all','Alimentación','Evento','Recuento'].map(x=>`<button class="${filter===x?'active':''}" data-filter="${x}">${x==='all'?'Todo':x}</button>`).join('')}</div><div class="timeline">${all.filter(x=>filter==='all'||x.kind===filter).map(x=>`<div class="timeline-item"><h3>${x.kind==='Alimentación'?'🍯':x.kind==='Evento'?'📅':'📈'} ${esc(x.title)}</h3><p>${esc(x.date||'Sin fecha')} · ${esc(colonyName(x.colonyId))}${x.notes?' · '+esc(x.notes):''}</p></div>`).join('')||'<div class="empty">Todavía no hay registros.</div>'}</div>`}
function stats(){const t=totals(),max=Math.max(...db.colonies.map(c=>+c.workers||0),1);return `<div class="section-title"><div><h2>Datos y crecimiento</h2><p>Resumen de tus colonias</p></div></div><div class="metric-grid"><div class="card"><b style="font-size:25px">${t.workers}</b><div class="sub">obreras totales</div></div><div class="card"><b style="font-size:25px">${db.growthRecords.length}</b><div class="sub">recuentos</div></div><div class="card"><b style="font-size:25px">${db.feedings.length}</b><div class="sub">alimentaciones</div></div><div class="card"><b style="font-size:25px">${db.events.length}</b><div class="sub">eventos</div></div></div><div class="section-title"><div><h2>Población actual</h2><p>Comparación aproximada</p></div></div><div class="cards">${db.colonies.map(c=>`<div class="card"><div style="display:flex;justify-content:space-between"><b>${esc(c.name)}</b><span class="sub">${+c.workers||0}</span></div><div class="progress" style="margin-top:10px"><span style="width:${Math.max(3,(+c.workers||0)/max*100)}%"></span></div><div class="sub"><i>${esc(c.species||'')}</i></div></div>`).join('')}</div><div class="section-title"><div><h2>Evolución</h2><p>Selecciona una colonia</p></div></div><select id="chartColony" style="width:100%;padding:12px;border-radius:14px;border:1px solid var(--line);background:var(--surface);color:var(--ink)">${db.colonies.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select><canvas id="chart" width="720" height="330" style="margin-top:10px"></canvas>`}
function more(){return `<div class="section-title"><div><h2>Más</h2><p>Configuración y copias</p></div></div><div class="cards"><div class="card"><b>☁️ Copia de seguridad</b><div class="sub">Incluye colonias, registros y fotografías.</div><div class="actions"><button class="button" id="export">Exportar</button><label class="button secondary" style="text-align:center">Importar<input id="import" type="file" accept="application/json" hidden></label></div></div><div class="card"><b>⏰ Nueva tarea</b><div class="sub">Crea recordatorios de alimentación, limpieza o revisión.</div><div class="actions"><button class="button secondary" data-quick="task">Crear recordatorio</button></div></div><div class="card"><b>📦 Inventario</b><div class="sub">${db.inventory.length} elementos registrados.</div><div class="actions"><button class="button secondary" data-inventory>Gestionar</button></div></div><div class="card"><b>ANTELMO V4</b><div class="sub">Datos almacenados localmente en tu dispositivo. Funciona sin conexión.</div></div></div>`}
function colonyOptions(sel=''){return db.colonies.map(c=>`<option value="${esc(c.id)}" ${String(c.id)===String(sel)?'selected':''}>${esc(c.name)}</option>`).join('')}
function field(label,html){return `<label>${label}${html}</label>`}
function feedingForm(id=''){openModal(`<h2>🍯 Registrar alimentación</h2><form id="feedForm" class="form">${field('Colonia',`<select name="colonyId" required>${colonyOptions(id)}</select>`)}<div class="row">${field('Fecha',`<input name="date" type="date" value="${today()}" required>`)}${field('Tipo',`<select name="category"><option>Semillas</option><option>Proteína</option><option>Néctar</option><option>Fruta</option><option>Otro</option></select>`)}</div>${field('Alimento',`<input name="food" placeholder="Chía, grillo, néctar…" required>`)}${field('Respuesta de la colonia',`<textarea name="notes" placeholder="Aceptación, comportamiento, restos…"></textarea>`)}<button class="button">Guardar alimentación</button></form>`);$('#feedForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));db.feedings.push({id:uid('feed'),...o});save();closeModal();toast('Alimentación guardada');render()}}
function eventForm(id=''){openModal(`<h2>📅 Registrar evento</h2><form id="eventForm" class="form">${field('Colonia',`<select name="colonyId">${colonyOptions(id)}</select>`)}<div class="row">${field('Fecha',`<input name="date" type="date" value="${today()}" required>`)}${field('Tipo',`<select name="type"><option>Observación</option><option>Mudanza</option><option>Limpieza</option><option>Hidratación</option><option>Incidencia</option><option>Nacimiento</option></select>`)}</div>${field('Título',`<input name="title" required>`)}${field('Notas',`<textarea name="notes"></textarea>`)}<button class="button">Guardar evento</button></form>`);$('#eventForm').onsubmit=e=>{e.preventDefault();db.events.push({id:uid('event'),...Object.fromEntries(new FormData(e.target))});save();closeModal();toast('Evento guardado');render()}}
function growthForm(id=''){openModal(`<h2>📈 Nuevo recuento</h2><form id="growthForm" class="form">${field('Colonia',`<select name="colonyId">${colonyOptions(id)}</select>`)}${field('Fecha',`<input name="date" type="date" value="${today()}" required>`)}<div class="row">${field('Obreras',`<input name="workers" type="number" min="0">`)}${field('Reinas',`<input name="queens" type="number" min="0" value="1">`)}</div><div class="row">${field('Huevos',`<input name="eggs" type="number" min="0">`)}${field('Larvas',`<input name="larvae" type="number" min="0">`)}</div>${field('Notas',`<textarea name="notes"></textarea>`)}<button class="button">Guardar recuento</button></form>`);$('#growthForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));['workers','queens','eggs','larvae'].forEach(k=>o[k]=o[k]===''?null:+o[k]);db.growthRecords.push({id:uid('growth'),...o});const c=db.colonies.find(x=>String(x.id)===String(o.colonyId));if(c){if(o.workers!=null)c.workers=o.workers;if(o.queens!=null)c.queens=o.queens;c.updatedAt=today()}save();closeModal();toast('Recuento guardado');render()}}
function taskForm(){openModal(`<h2>⏰ Nuevo recordatorio</h2><form id="taskForm" class="form">${field('Título',`<input name="title" required>`)}<div class="row">${field('Fecha',`<input name="dueDate" type="date" value="${today()}">`)}${field('Prioridad',`<select name="priority"><option>Normal</option><option>Alta</option><option>Baja</option></select>`)}</div><button class="button">Guardar recordatorio</button></form>`);$('#taskForm').onsubmit=e=>{e.preventDefault();db.tasks.push({id:uid('task'),status:'Pendiente',...Object.fromEntries(new FormData(e.target))});save();closeModal();toast('Recordatorio guardado');render()}}
function colonyForm(id){const c=db.colonies.find(x=>String(x.id)===String(id))||{};openModal(`<h2>${id?'Editar':'Nueva'} colonia</h2><form id="colonyForm" class="form">${field('Nombre',`<input name="name" value="${esc(c.name||'')}" required>`)}${field('Especie',`<input name="species" value="${esc(c.species||'')}">`)}<div class="row">${field('Obreras',`<input name="workers" type="number" min="0" value="${esc(c.workers??0)}">`)}${field('Reinas',`<input name="queens" type="number" min="0" value="${esc(c.queens??1)}">`)}</div><div class="row">${field('Estado',`<select name="status">${['Crecimiento','Estable','En observación','En tránsito'].map(x=>`<option ${c.status===x?'selected':''}>${x}</option>`).join('')}</select>`)}${field('Fecha de inicio',`<input name="founded" type="date" value="${esc(c.founded||today())}">`)}</div>${field('Instalación',`<input name="location" value="${esc(c.location||'')}">`)}${field('Notas',`<textarea name="notes">${esc(c.notes||'')}</textarea>`)}<button class="button">Guardar colonia</button>${id?'<button type="button" class="button danger" id="deleteColony">Eliminar colonia</button>':''}</form>`);$('#colonyForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.workers=+o.workers||0;o.queens=+o.queens||0;if(id)Object.assign(c,o,{updatedAt:today()});else db.colonies.push({id:uid('colony'),...o,createdAt:today(),updatedAt:today()});save();closeModal();toast('Colonia guardada');selected=id||null;render()};if(id)$('#deleteColony').onclick=()=>{if(confirm('¿Eliminar esta colonia?')){db.colonies=db.colonies.filter(x=>String(x.id)!==String(id));save();selected=null;closeModal();render()}}}
function photoForm(id=''){openModal(`<h2>📷 Añadir fotografía</h2><form id="photoForm" class="form">${field('Colonia',`<select name="colonyId">${colonyOptions(id)}</select>`)}${field('Fecha',`<input name="date" type="date" value="${today()}">`)}${field('Foto',`<input name="photo" type="file" accept="image/*" capture="environment" required>`)}${field('Descripción',`<input name="caption" placeholder="Cría, reina, instalación…">`)}<label><input name="cover" type="checkbox"> Usar como portada</label><button class="button">Guardar fotografía</button></form>`);$('#photoForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),file=fd.get('photo');if(!file?.size)return;const colonyId=fd.get('colonyId'),cover=fd.get('cover')==='on';if(cover)await clearCovers(colonyId);await photoPut({id:uid('photo'),colonyId,date:fd.get('date'),caption:fd.get('caption'),cover,blob:file});closeModal();toast('Fotografía guardada');render()}}
function inventoryForm(){openModal(`<h2>📦 Inventario</h2><div class="cards">${db.inventory.map(x=>`<div class="card"><b>${esc(x.name)}</b><div class="sub">${esc(x.quantity||1)} · ${esc(x.notes||'')}</div></div>`).join('')||'<div class="empty">Inventario vacío.</div>'}</div><form id="inventoryForm" class="form" style="margin-top:14px">${field('Elemento',`<input name="name" required>`)}<div class="row">${field('Cantidad',`<input name="quantity" type="number" value="1" min="1">`)}${field('Categoría',`<select name="category"><option>Hormiguero</option><option>Alimento</option><option>Accesorio</option><option>Otro</option></select>`)}</div>${field('Notas',`<input name="notes">`)}<button class="button">Añadir</button></form>`);$('#inventoryForm').onsubmit=e=>{e.preventDefault();db.inventory.push({id:uid('item'),...Object.fromEntries(new FormData(e.target))});save();inventoryForm()}}
function bind(){
 $$('[data-go]').forEach(x=>x.onclick=()=>{route=x.dataset.go;render()});$$('[data-colony]').forEach(x=>x.onclick=()=>{route='colonies';selected=x.dataset.colony;render()});$$('[data-filter]').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;render()});
 $$('[data-quick]').forEach(x=>x.onclick=()=>({feed:feedingForm,event:eventForm,growth:growthForm,photo:photoForm,task:taskForm}[x.dataset.quick]?.()));
 $$('[data-done]').forEach(x=>x.onclick=()=>{const t=db.tasks.find(y=>String(y.id)===x.dataset.done);if(t){t.status='Completada';save();render()}});
 $('[data-back]')&&($('[data-back]').onclick=()=>{selected=null;render()});$('[data-new-colony]')&&($('[data-new-colony]').onclick=()=>colonyForm());$('[data-edit-colony]')&&($('[data-edit-colony]').onclick=e=>colonyForm(e.currentTarget.dataset.editColony));$('[data-photo-for]')&&($('[data-photo-for]').onclick=e=>photoForm(e.currentTarget.dataset.photoFor));
 $('#chartColony')&&($('#chartColony').onchange=drawChart,drawChart());$('#export')&&($('#export').onclick=()=>exportBackup(true));$('#import')&&($('#import').onchange=e=>importBackup(e.target.files[0]));$('[data-inventory]')&&($('[data-inventory]').onclick=inventoryForm);
 if(selected)loadGallery(selected)
}
function drawChart(){const canvas=$('#chart');if(!canvas)return;const id=$('#chartColony').value,arr=db.growthRecords.filter(x=>String(x.colonyId)===String(id)&&x.workers!=null).sort((a,b)=>String(a.date).localeCompare(String(b.date))),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const css=getComputedStyle(document.body),ink=css.getPropertyValue('--ink').trim(),line=css.getPropertyValue('--line').trim(),green=css.getPropertyValue('--green2').trim();ctx.strokeStyle=line;ctx.lineWidth=1;for(let i=0;i<5;i++){const y=35+i*60;ctx.beginPath();ctx.moveTo(52,y);ctx.lineTo(690,y);ctx.stroke()}if(!arr.length){ctx.fillStyle=ink;ctx.font='18px sans-serif';ctx.fillText('Aún no hay recuentos para esta colonia',185,165);return}const max=Math.max(...arr.map(x=>+x.workers),1),min=Math.min(...arr.map(x=>+x.workers),0);ctx.strokeStyle=green;ctx.lineWidth=5;ctx.beginPath();arr.forEach((p,i)=>{const x=65+(arr.length===1?300:i*600/(arr.length-1)),y=285-((p.workers-min)/(max-min||1))*220;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=green;arr.forEach((p,i)=>{const x=65+(arr.length===1?300:i*600/(arr.length-1)),y=285-((p.workers-min)/(max-min||1))*220;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();ctx.fillStyle=ink;ctx.font='13px sans-serif';ctx.fillText(String(p.workers),x-7,y-12);ctx.fillText(String(p.date).slice(5),x-18,310);ctx.fillStyle=green})}
function initIDB(){return new Promise(r=>{const req=indexedDB.open('antelmo-media',1);req.onupgradeneeded=e=>{if(!e.target.result.objectStoreNames.contains('photos'))e.target.result.createObjectStore('photos',{keyPath:'id'})};req.onsuccess=e=>{idb=e.target.result;r()};req.onerror=()=>r()})}
function store(mode='readonly'){return idb.transaction('photos',mode).objectStore('photos')}
const photoAll=()=>new Promise(r=>{if(!idb)return r([]);const q=store().getAll();q.onsuccess=()=>r(q.result||[]);q.onerror=()=>r([])}),photoPut=p=>new Promise((r,j)=>{const q=store('readwrite').put(p);q.onsuccess=r;q.onerror=j}),photoDelete=id=>new Promise(r=>{const q=store('readwrite').delete(id);q.onsuccess=r}),photosByColony=async id=>(await photoAll()).filter(p=>String(p.colonyId)===String(id)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
async function clearCovers(id){for(const p of await photosByColony(id)){if(p.cover){p.cover=false;await photoPut(p)}}}
async function loadCovers(){if(!idb)return;for(const c of db.colonies){const el=$(`#cover-${CSS.escape(String(c.id))}`);if(!el)continue;const ps=await photosByColony(c.id),p=ps.find(x=>x.cover)||ps[0];if(p)el.innerHTML=`<img alt="${esc(c.name)}" src="${URL.createObjectURL(p.blob)}">`}}
async function loadGallery(id){const el=$('#gallery');if(!el)return;const ps=await photosByColony(id);el.innerHTML=ps.map(p=>`<div class="photo"><img src="${URL.createObjectURL(p.blob)}" alt="${esc(p.caption||'Fotografía')}"><button data-del-photo="${esc(p.id)}">×</button></div>`).join('')||'<div class="empty">Todavía no hay fotografías.</div>';$$('[data-del-photo]').forEach(b=>b.onclick=async()=>{await photoDelete(b.dataset.delPhoto);loadGallery(id);loadCovers()})}
const blobToDataURL=b=>new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(b)});
async function exportBackup(share=false){const media=[];for(const p of await photoAll())media.push({...p,blob:undefined,dataUrl:await blobToDataURL(p.blob),mime:p.blob.type});const backup={...db,mediaBackup:media,metadata:{...(db.metadata||{}),schemaVersion:'4.0.0',exportedAt:new Date().toISOString()}};const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),file=new File([blob],`ANTELMO-V4-${today()}.json`,{type:'application/json'});if(share&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Copia ANTELMO V4'});else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}toast('Copia creada')}
async function importBackup(file){if(!file)return;try{const x=JSON.parse(await file.text());if(!Array.isArray(x.colonies))throw Error();const media=x.mediaBackup||[];delete x.mediaBackup;db=x;for(const p of media){const blob=await fetch(p.dataUrl).then(r=>r.blob());await photoPut({...p,blob,dataUrl:undefined})}save();toast('Copia importada');render()}catch{alert('La copia no es válida')}}
$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#fab').onclick=()=>openModal(`<h2>Nuevo registro</h2><div class="quick-grid"><button class="quick" id="mfeed"><i>🍯</i><b>Alimentación</b></button><button class="quick" id="mevent"><i>📅</i><b>Evento</b></button><button class="quick" id="mgrowth"><i>📈</i><b>Recuento</b></button><button class="quick" id="mphoto"><i>📷</i><b>Fotografía</b></button></div>`);document.addEventListener('click',e=>{if(e.target.closest('#mfeed'))feedingForm();if(e.target.closest('#mevent'))eventForm();if(e.target.closest('#mgrowth'))growthForm();if(e.target.closest('#mphoto'))photoForm()});$('#themeBtn').onclick=()=>{db.appConfig ||= {};db.appConfig.theme=db.appConfig.theme==='dark'?'light':'dark';save();applyTheme();render()};boot();
