/* ANTELMO V6 — Mesa viva, analítica, cuidados inteligentes, terrarios y laboratorio multimedia */
const v6BaseHome=home, v6BaseStats=stats, v6BaseMore=more, v6BaseBind=bind, v6BasePhotoForm=photoForm, v6BaseLoadGallery=loadGallery, v6BaseFaunaView=faunaView, v6BaseDueAlerts=dueAlerts;

function ensureV6Data(){
  ensureV5Data?.(); ensureProData?.();
  db.faunaLogs ||= [];
  db.smartRules ||= {photoDays:14, hydrationDays:5, feedingEnabled:true, photoEnabled:true};
  db.mediaPrefs ||= {galleryFilter:'all',gallerySearch:''};
  db.appConfig ||= {};
  if(nav?.[0]) nav[0][2]='Mesa';
  if(nav?.[1]) nav[1][2]='AntDex';
}
const v6BaseSave=save;
save=function(){ensureV6Data();db.metadata={...(db.metadata||{}),schemaVersion:'6.0.0',updatedAt:new Date().toISOString()};localStorage.setItem('antelmo.v4',JSON.stringify(db));};

function daysFromDate(d){if(!d)return null;return Math.max(0,Math.floor((new Date(today())-new Date(d))/86400000))}
function colonyActivity(c){
 const feed=lastFeeding(c.id), events=db.events.filter(x=>String(x.colonyId)===String(c.id)).sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0], growth=db.growthRecords.filter(x=>String(x.colonyId)===String(c.id)).sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0];
 return [feed?.date,events?.date,growth?.date,c.updatedAt].filter(Boolean).sort().at(-1)||c.founded;
}
function healthSignal(c){const fd=daysSince(lastFeeding(c.id)?.date), latestScan=db.scanReports.filter(x=>String(x.colonyId)===String(c.id)).at(-1);if(latestScan?.flags?.some(x=>['mold','stress'].includes(x)))return ['attention','⚠️','Revisar'];if(fd==null||fd>=+(db.appConfig.feedingAlertDays||4))return ['due','🍯','Alimentar'];return ['good','●','Al día']}
function workbenchCard(c){const [cls,icon,label]=healthSignal(c),activity=colonyActivity(c);return `<article class="workbench-card ${cls}" data-colony="${esc(c.id)}"><div class="workbench-cover avatar" id="cover-${esc(c.id)}">🐜</div><div class="workbench-body"><div class="workbench-head"><div><span class="dex-mini">ANTDEX #${String(db.colonies.indexOf(c)+1).padStart(3,'0')}</span><h3>${esc(c.name)}</h3><p class="latin">${esc(c.species||'Especie sin confirmar')}</p></div><span class="health-pill ${cls}">${icon} ${label}</span></div><div class="living-stats"><span><b>${esc(c.workers??'—')}</b> obreras</span><span><b>${esc(c.queens??'—')}</b> reina${+c.queens===1?'':'s'}</span><span><b>Nv. ${rankFor(c)}</b> rango</span></div><div class="population-track"><i style="width:${Math.max(4,Math.min(100,(+c.workers||0)/Math.max(...db.colonies.map(x=>+x.workers||0),1)*100))}%"></i></div><small>${activity?`Última actividad: ${esc(activity)}`:'Sin actividad registrada'}</small></div></article>`}

function smartCareItems(){ensureV6Data();const out=[];const photoDays=+db.smartRules.photoDays||14;db.colonies.forEach(c=>{const f=lastFeeding(c.id),fd=daysSince(f?.date);if(db.smartRules.feedingEnabled&&(fd==null||fd>=+(db.appConfig.feedingAlertDays||4)))out.push({icon:'🍯',title:c.name,text:fd==null?'No tiene alimentación registrada':`Han pasado ${fd} días desde la última alimentación`,colonyId:c.id,action:'feed'});const activity=daysFromDate(colonyActivity(c));if(db.smartRules.photoEnabled&&activity!=null&&activity>=photoDays)out.push({icon:'📸',title:c.name,text:`Lleva ${activity} días sin actividad visual o recuento`,colonyId:c.id,action:'photo'});});return out.slice(0,12)}

home=function(){ensureV6Data();const t=totals(),care=smartCareItems();return `<section class="v6-hero"><div><span class="eyebrow">CENTRO DE MANDO</span><h2>Tu mesa de trabajo</h2><p>${t.colonies} colonias · ${t.workers} obreras · ${db.fauna.length} habitantes de terrario</p></div><button class="button glass" data-quick="photo">📸 Registrar</button></section><div class="care-strip">${care.slice(0,4).map(x=>`<button data-smart-action="${x.action}" data-smart-colony="${esc(x.colonyId)}"><span>${x.icon}</span><div><b>${esc(x.title)}</b><small>${esc(x.text)}</small></div></button>`).join('')||'<div class="care-clear">🌿 Todo parece al día</div>'}</div><div class="section-title"><div><h2>Colonias vivas</h2><p>Toca una tarjeta para abrir su AntDex</p></div><button class="link-btn" data-go="colonies">Ver lista</button></div><div class="workbench-grid">${db.colonies.map(workbenchCard).join('')||'<div class="empty">Añade tu primera colonia.</div>'}</div><div class="dashboard-shortcuts"><button data-v6-dest="analytics"><span>📊</span><b>Analítica</b><small>Gráficas ampliadas</small></button><button data-v6-dest="smart"><span>🧠</span><b>Cuidados</b><small>Agenda inteligente</small></button><button data-v6-dest="fauna"><span>🪲</span><b>Terrarios</b><small>Fauna y observaciones</small></button><button data-v6-dest="media"><span>🎞️</span><b>Laboratorio</b><small>Fotos y comparaciones</small></button></div>`}

function metricSeries(c,metric){return db.growthRecords.filter(x=>String(x.colonyId)===String(c.id)&&x[metric]!=null).sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(x=>({date:x.date,value:+x[metric]||0}))}
function sparklineSvg(arr){if(!arr.length)return '<div class="empty mini">Sin datos</div>';const w=300,h=90,max=Math.max(...arr.map(x=>x.value),1),min=Math.min(...arr.map(x=>x.value),0),pts=arr.map((x,i)=>`${10+(arr.length===1?140:i*280/(arr.length-1))},${80-((x.value-min)/(max-min||1))*65}`).join(' ');return `<svg class="sparkline" viewBox="0 0 ${w} ${h}" role="img"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>${arr.map((x,i)=>`<circle cx="${10+(arr.length===1?140:i*280/(arr.length-1))}" cy="${80-((x.value-min)/(max-min||1))*65}" r="4" fill="currentColor"/>`).join('')}</svg>`}
function analyticsView(){const metric=db.appConfig.v6Metric||'workers';return `<div class="section-title"><div><h2>📊 Analítica avanzada</h2><p>Obreras, huevos, larvas y pupas</p></div></div><div class="metric-switch">${[['workers','Obreras'],['eggs','Huevos'],['larvae','Larvas'],['pupae','Pupas']].map(([k,l])=>`<button class="${metric===k?'active':''}" data-v6-metric="${k}">${l}</button>`).join('')}</div><div class="analytics-grid">${db.colonies.map(c=>{const arr=metricSeries(c,metric),delta=arr.length>1?arr.at(-1).value-arr[0].value:null;return `<article class="card analytic-card"><div><b>${esc(c.name)}</b><span>${arr.length?`${arr.at(-1).value} actuales`:'Sin recuentos'}</span></div>${sparklineSvg(arr)}<small>${delta==null?'Añade al menos dos recuentos':delta>0?`↗ Crecimiento +${delta}`:delta<0?`↘ Variación ${delta}`:'➡ Sin variación'}</small></article>`}).join('')}</div><div class="section-title"><div><h2>Actividad registrada</h2><p>Resumen global</p></div></div><div class="metric-grid"><div class="card"><b class="big-number">${db.feedings.length}</b><div class="sub">alimentaciones</div></div><div class="card"><b class="big-number">${db.events.length}</b><div class="sub">eventos</div></div><div class="card"><b class="big-number">${db.growthRecords.length}</b><div class="sub">recuentos</div></div><div class="card"><b class="big-number">${db.scanReports.length}</b><div class="sub">AntScan</div></div></div>`}

stats=function(){ensureV6Data();return analyticsView()}

function smartCareView(){const items=smartCareItems();return `<div class="section-title"><div><h2>🧠 Calendario inteligente</h2><p>Sugerencias creadas a partir de tus registros</p></div></div><div class="cards">${items.map(x=>`<article class="card smart-care"><span>${x.icon}</span><div><b>${esc(x.title)}</b><p>${esc(x.text)}</p></div><button class="button secondary" data-smart-action="${x.action}" data-smart-colony="${esc(x.colonyId)}">Registrar</button></article>`).join('')||'<div class="card empty">No hay sugerencias pendientes 🌱</div>'}</div><div class="section-title"><div><h2>Reglas</h2><p>Ajusta cuándo debe avisarte</p></div></div><div class="card form"><label>Foto o revisión tras <b id="photoDaysLabel">${db.smartRules.photoDays} días</b><input id="photoDaysRule" type="range" min="3" max="45" value="${db.smartRules.photoDays}"></label><label class="check-row"><input id="smartFeeding" type="checkbox" ${db.smartRules.feedingEnabled?'checked':''}> Sugerir alimentaciones pendientes</label><label class="check-row"><input id="smartPhotos" type="checkbox" ${db.smartRules.photoEnabled?'checked':''}> Sugerir fotografías de seguimiento</label></div>${calendarView()}`}

function faunaLogForm(id){const f=db.fauna.find(x=>String(x.id)===String(id));if(!f)return;openModal(`<h2>${esc(f.emoji||'🪲')} Observación de ${esc(f.name)}</h2><form id="faunaLogForm" class="form">${field('Fecha',`<input name="date" type="date" value="${today()}">`)}${field('Tipo',`<select name="type"><option>Observación</option><option>Alimentación</option><option>Limpieza</option><option>Cambio de hábitat</option><option>Salud</option></select>`)}${field('Notas',`<textarea name="notes" required placeholder="Actividad, comida, refugio, comportamiento…"></textarea>`)}<button class="button">Guardar</button></form>`);$('#faunaLogForm').onsubmit=e=>{e.preventDefault();db.faunaLogs.push({id:uid('flog'),faunaId:id,...Object.fromEntries(new FormData(e.target))});save();closeModal();toast('Observación guardada');render()}}
function terrariumView(){return `<div class="section-title"><div><h2>🪲 Modo Terrario</h2><p>Habitantes, cuidados e historial</p></div><button class="button" data-new-fauna>＋ Habitante</button></div><div class="terrarium-grid">${db.fauna.map(x=>{const logs=db.faunaLogs.filter(l=>String(l.faunaId)===String(x.id)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return `<article class="terrarium-card"><div class="terrarium-emoji">${esc(x.emoji||'🪲')}</div><div><span class="chip">${esc(x.status||'Activo')}</span><h3>${esc(x.name)}</h3><p class="latin">${esc(x.species||'Especie sin confirmar')}</p><small>${esc(x.habitat||'Sin hábitat')}</small><div class="terrarium-last">${logs[0]?`<b>${esc(logs[0].type)}</b><span>${esc(logs[0].date)} · ${esc(logs[0].notes)}</span>`:'Sin observaciones todavía'}</div><div class="actions"><button class="button secondary" data-fauna-log="${esc(x.id)}">＋ Observación</button><button class="icon-btn" data-edit-fauna="${esc(x.id)}">✎</button></div></div></article>`}).join('')||'<div class="empty">Añade a Blas, Sansón, Tuna, Chin y futuros habitantes.</div>'}</div>`}

function mediaLabView(){const colonies=db.colonies;return `<div class="section-title"><div><h2>🎞️ Laboratorio visual</h2><p>Busca, filtra y compara la evolución</p></div><button class="button" data-quick="photo">＋ Multimedia</button></div><div class="card media-controls"><select id="mediaColony"><option value="">Todas las colonias</option>${colonyOptions()}</select><input id="mediaSearch" placeholder="Buscar descripción…"><button class="button secondary" id="mediaLoad">Mostrar</button></div><div id="mediaLabGrid" class="gallery gallery-rich"><div class="empty">Pulsa Mostrar para cargar la galería.</div></div><div class="card compare-panel"><b>Antes / Después</b><p class="sub">Marca dos fotografías y pulsa comparar.</p><button class="button" id="compareSelected">Comparar seleccionadas</button></div>`}
async function renderMediaLab(){const el=$('#mediaLabGrid');if(!el)return;const colony=$('#mediaColony')?.value||'',q=($('#mediaSearch')?.value||'').toLowerCase();let ps=await photoAll();ps=ps.filter(p=>(!colony||String(p.colonyId)===String(colony))&&(!q||(p.caption||'').toLowerCase().includes(q)));el.innerHTML=ps.map(p=>{const url=URL.createObjectURL(p.blob),video=p.blob?.type?.startsWith('video/');return `<article class="photo-card lab-media"><label class="compare-check"><input type="checkbox" data-compare-id="${esc(p.id)}"></label>${video?`<video controls preload="metadata" src="${url}"></video>`:`<button class="photo-open" data-view-photo="${esc(p.id)}"><img src="${url}" alt="${esc(p.caption||'Fotografía')}"></button>`}<div class="photo-meta"><div><b>${esc(p.caption||'Sin descripción')}</b><span>${esc(p.date||'Sin fecha')} · ${esc(colonyName(p.colonyId))}</span></div></div></article>`}).join('')||'<div class="empty">No hay resultados.</div>';$$('[data-view-photo]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>String(x.id)===String(b.dataset.viewPhoto));if(p)viewPhoto(p,b.querySelector('img').src,p.colonyId)})}
async function compareMedia(){const ids=$$('[data-compare-id]:checked').map(x=>x.dataset.compareId);if(ids.length!==2)return toast('Marca exactamente dos fotografías');const ps=await photoAll(),selectedPhotos=ids.map(id=>ps.find(p=>String(p.id)===String(id))).filter(Boolean);if(selectedPhotos.some(p=>p.blob?.type?.startsWith('video/')))return toast('La comparación es para fotografías');openModal(`<h2>Antes / Después</h2><div class="before-after">${selectedPhotos.map((p,i)=>`<figure><img src="${URL.createObjectURL(p.blob)}"><figcaption><b>${i?'Después':'Antes'}</b><span>${esc(p.date||'Sin fecha')} · ${esc(p.caption||'')}</span></figcaption></figure>`).join('')}</div>`)}

photoForm=function(id=''){openModal(`<h2>📸 Añadir multimedia</h2><p class="modal-intro">Elige fotografías o vídeos del iPhone. Las fotografías se optimizan; los vídeos se guardan en su formato original.</p><form id="photoForm" class="form">${field('Colonia',`<select name="colonyId">${colonyOptions(id)}</select>`)}${field('Fecha',`<input name="date" type="date" value="${today()}">`)}${field('Fotos o vídeo',`<input name="photo" type="file" accept="image/*,video/*" multiple required><small class="field-help">Puedes elegir varias fotografías o un vídeo.</small>`)}${field('Descripción común',`<input name="caption" placeholder="Llegada, cría, mudanza, timelapse…">`)}<label class="check-row"><input name="cover" type="checkbox"> Usar la primera fotografía como portada</label><button class="button">Guardar</button></form>`);$('#photoForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),files=[...e.target.elements.photo.files];if(!files.length)return;const colonyId=fd.get('colonyId'),cover=fd.get('cover')==='on';if(cover)await clearCovers(colonyId);let i=0;for(const file of files){const isImage=file.type.startsWith('image/'),blob=isImage?await optimizeImage(file):file;await photoPut({id:uid('media'),colonyId,date:fd.get('date'),caption:fd.get('caption')||(files.length>1?`Archivo ${i+1}`:''),cover:cover&&i===0&&isImage,blob,createdAt:new Date().toISOString()});i++}closeModal();toast(`${files.length} archivo${files.length===1?'':'s'} guardado${files.length===1?'':'s'}`);render()}}

loadGallery=async function(id){const el=$('#gallery');if(!el)return;const ps=await photosByColony(id);el.innerHTML=ps.map(p=>{const url=URL.createObjectURL(p.blob),video=p.blob?.type?.startsWith('video/');return `<article class="photo-card ${p.cover?'is-cover':''}">${video?`<video controls preload="metadata" src="${url}"></video>`:`<button class="photo-open" data-view-photo="${esc(p.id)}"><img src="${url}" alt="${esc(p.caption||'Fotografía')}"></button>`}<div class="photo-meta"><div><b>${esc(p.caption||'Sin descripción')}</b><span>${esc(p.date||'Sin fecha')}</span></div>${p.cover?'<span class="cover-badge">⭐ Portada</span>':''}</div><div class="photo-actions">${video?'':`<button data-cover-photo="${esc(p.id)}">⭐</button>`}<button data-edit-photo="${esc(p.id)}">✎</button><button class="danger-icon" data-del-photo="${esc(p.id)}">🗑</button></div></article>`}).join('')||'<div class="empty gallery-empty"><b>Tu álbum está vacío</b><span>Añade fotografías o vídeos.</span></div>';$$('[data-view-photo]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>String(x.id)===String(b.dataset.viewPhoto));if(p)viewPhoto(p,b.querySelector('img').src,id)});$$('[data-cover-photo]').forEach(b=>b.onclick=()=>setPhotoCover(b.dataset.coverPhoto,id));$$('[data-edit-photo]').forEach(b=>b.onclick=()=>editPhoto(b.dataset.editPhoto,id));$$('[data-del-photo]').forEach(b=>b.onclick=async()=>{if(confirm('¿Eliminar este archivo?')){await photoDelete(b.dataset.delPhoto);loadGallery(id);loadCovers()}})}

function syncView(){return `<div class="section-title"><div><h2>☁️ Sincronización portátil</h2><p>Mueve ANTELMO entre iPhone, iPad, Mac y Windows</p></div></div><div class="cards"><div class="card sync-card"><span>📦</span><div><b>Crear paquete completo</b><p>Incluye colonias, fotos, vídeos, fauna, mediciones y configuración.</p></div><button class="button" id="export">Exportar / compartir</button></div><div class="card sync-card"><span>📥</span><div><b>Restaurar paquete</b><p>Importa un archivo de ANTELMO guardado en Archivos, iCloud Drive o Google Drive.</p></div><label class="button secondary">Importar<input id="import" type="file" accept="application/json" hidden></label></div><div class="card privacy-note"><b>🔒 Privacidad</b><p>ANTELMO sigue siendo local. La sincronización automática en segundo plano necesitaría un servicio de nube, inicio de sesión y servidor propios. Esta versión usa paquetes portátiles para no exponer tus datos.</p></div></div>`}

more=function(){ensureV6Data();const tab=db.appConfig.moreTab||'tools',tabs=[['tools','Centro'],['smart','Cuidados'],['media','Galería'],['fauna','Terrarios'],['encyclopedia','Enciclopedia'],['scanner','AntScan'],['achievements','Logros'],['sync','Sincronizar'],['environment','Ambiente'],['search','Buscar']];const bar=`<div class="tabs pro-tabs">${tabs.map(([k,l])=>`<button class="${tab===k?'active':''}" data-more-tab="${k}">${l}</button>`).join('')}</div>`;if(tab==='smart')return bar+smartCareView();if(tab==='media')return bar+mediaLabView();if(tab==='fauna')return bar+terrariumView();if(tab==='sync')return bar+syncView();if(['encyclopedia','scanner','achievements','environment','search'].includes(tab)){const html=v6BaseMore();return html.replace(/<div class="tabs pro-tabs">[\s\S]*?<\/div>/,bar)}return bar+`<div class="section-title"><div><h2>Centro ANTELMO 6</h2><p>Todo tu ecosistema en un solo lugar</p></div></div><div class="dashboard-shortcuts wide"><button data-v6-dest="smart"><span>🧠</span><b>Cuidados inteligentes</b><small>Alertas y calendario</small></button><button data-v6-dest="media"><span>🎞️</span><b>Laboratorio visual</b><small>Comparar evolución</small></button><button data-v6-dest="fauna"><span>🪲</span><b>Modo Terrario</b><small>Fauna e historial</small></button><button data-v6-dest="sync"><span>☁️</span><b>Sincronizar</b><small>Paquetes portátiles</small></button></div>`}

dueAlerts=function(){return [...v6BaseDueAlerts(),...smartCareItems().map(x=>({level:'warn',icon:x.icon,title:x.title,text:x.text}))].slice(0,10)}

bind=function(){v6BaseBind();ensureV6Data();$$('[data-v6-dest]').forEach(b=>b.onclick=()=>{const d=b.dataset.v6Dest;if(d==='analytics'){route='stats'}else{route='more';db.appConfig.moreTab=d}save();render()});$$('[data-smart-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.smartColony,act=b.dataset.smartAction;if(act==='feed')feedingForm(id);else photoForm(id)});$$('[data-v6-metric]').forEach(b=>b.onclick=()=>{db.appConfig.v6Metric=b.dataset.v6Metric;save();render()});$('#photoDaysRule')&&($('#photoDaysRule').oninput=e=>{db.smartRules.photoDays=+e.target.value;$('#photoDaysLabel').textContent=e.target.value+' días';save()});$('#smartFeeding')&&($('#smartFeeding').onchange=e=>{db.smartRules.feedingEnabled=e.target.checked;save()});$('#smartPhotos')&&($('#smartPhotos').onchange=e=>{db.smartRules.photoEnabled=e.target.checked;save()});$$('[data-fauna-log]').forEach(b=>b.onclick=()=>faunaLogForm(b.dataset.faunaLog));$('#mediaLoad')&&($('#mediaLoad').onclick=renderMediaLab);$('#compareSelected')&&($('#compareSelected').onclick=compareMedia)}

const v6BaseBoot=boot;
boot=async function(){await v6BaseBoot();ensureV6Data();save();};

/* Portadas V6: ignorar vídeos y usar únicamente imágenes */
loadCovers=async function(){if(!idb)return;for(const c of db.colonies){const el=$(`#cover-${CSS.escape(String(c.id))}`);if(!el)continue;const ps=(await photosByColony(c.id)).filter(p=>p.blob?.type?.startsWith('image/'));const p=ps.find(x=>x.cover)||ps[0];if(p)el.innerHTML=`<img alt="${esc(c.name)}" src="${URL.createObjectURL(p.blob)}">`;else el.textContent='🐜'}};
